# Permalinks
permalink: pretty

# Site identity
title: Teamcenter 2412 Installation Runbook
url: "https://gitcak.github.io"
baseurl: "/TC_Runbook"

# Doc Assembler source types (processed as Markdown by Jekyll)
markdown_ext: markdown,tsfrg,tsgde,md

defaults:
  - scope:
      path: ""
    values:
      layout: "simple"
